name       : lbry-app
version    : 0.17.1
release    : 7
source     :
    - https://github.com/lbryio/lbry-app/archive/v0.17.1.tar.gz : b9d65fae7c0e9432d61e19c64d6b0fa87b538e821c0c9999170ad89bd4476fe8
license    : MIT
component  : multimedia.video
networking : yes
summary    : This is a graphical browser for the decentralized content marketplace provided by the LBRY protocol.
description: |
    This is a graphical browser for the decentralized content marketplace provided by the LBRY protocol.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - wget
    - yarn
setup      : |
    ./build.sh
build      : |
    node_modules/.bin/build --linux dir --x64 -p never
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00644 $installdir/usr/share/lbry-app
    cp -R dist/linux-unpacked/* $installdir/usr/share/lbry-app/
    ln -s /usr/share/lbry-app/lbry $installdir/usr/bin/lbry
    install -Dm00644 $pkgfiles/lbry-app.desktop $installdir/usr/share/applications/lbry-app.desktop
    install -Dm00644 build/icons/256x256.png $installdir/usr/share/pixmaps/lbry.png
