name       : lbry-desktop
version    : 0.37.2
release    : 48
source     :
    - https://github.com/lbryio/lbry-desktop/archive/v0.37.2.tar.gz : 288649379ba24c31ac9444bed529a384406ca74aa44f8a4304c9d2f61d140fc0
license    : MIT
component  : multimedia.video
networking : yes
summary    : This is a graphical browser for the decentralized content marketplace provided by the LBRY protocol
description: |
    This is a graphical browser for the decentralized content marketplace provided by the LBRY protocol.
replaces   :
    - lbry-app
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - git
    - wget
    - yarn
setup      : |
    yarn
build      : |
    yarn build:dir
    for arch in arm arm64 ia32; do
        find . -name "${arch}" -type d -exec rm -rf {} +
    done
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00644 $installdir/usr/share/lbry-desktop
    cp -R dist/electron/linux-unpacked/* $installdir/usr/share/lbry-desktop/
    ln -s /usr/share/lbry-desktop/LBRY $installdir/usr/bin/lbry
    install -Dm00644 $pkgfiles/lbry-desktop.desktop $installdir/usr/share/applications/lbry-desktop.desktop
    install -Dm00644 build/icons/256x256.png $installdir/usr/share/pixmaps/lbry.png
    # App update disable mechanism
    touch $installdir/usr/share/lbry-desktop/resources/static/upgradeDisabled
    chmod 00644 $installdir/usr/share/lbry-desktop/resources/static/upgradeDisabled
