name       : lbry-app
version    : 0.22.1
release    : 23
source     :
    - https://github.com/lbryio/lbry-app/archive/v0.22.1.tar.gz : dc354a5fa24dd2e27052fb2ce9d5dba4eb4a14c350caee73167964fb610b3dfa
license    : MIT
component  : multimedia.video
networking : yes
summary    : This is a graphical browser for the decentralized content marketplace provided by the LBRY protocol.
description: |
    This is a graphical browser for the decentralized content marketplace provided by the LBRY protocol.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - wget
    - yarn
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-upgrade-prompting-until-there-is-an-upstream.patch
    %patch -p1 < $pkgfiles/0001-Force-x64.patch
    yarn
build      : |
    yarn build:dir
    for arch in arm arm64 ia32; do
        find . -name "${arch}" -type d -exec rm -rf {} +
    done
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00644 $installdir/usr/share/lbry-app
    cp -R dist/linux-unpacked/* $installdir/usr/share/lbry-app/
    ln -s /usr/share/lbry-app/lbry $installdir/usr/bin/lbry
    install -Dm00644 $pkgfiles/lbry-app.desktop $installdir/usr/share/applications/lbry-app.desktop
    install -Dm00644 build/icons/256x256.png $installdir/usr/share/pixmaps/lbry.png
