name       : lbry-desktop
version    : 0.26.0
release    : 32
source     :
    - https://github.com/lbryio/lbry-desktop/archive/v0.26.0.tar.gz : 77212ccae97d4b377d560721a314060d6d1f2c55a3f1fa09e58348b980fae8a9
license    : MIT
component  : multimedia.video
networking : yes
summary    : This is a graphical browser for the decentralized content marketplace provided by the LBRY protocol
description: |
    This is a graphical browser for the decentralized content marketplace provided by the LBRY protocol.
replaces   :
    - lbry-app
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - wget
    - yarn
setup      : |
    %patch -p1 < $pkgfiles/0001-Force-x64-and-strip-out-upgrade-prompting.patch
    yarn
build      : |
    yarn build:dir
    for arch in arm arm64 ia32; do
        find . -name "${arch}" -type d -exec rm -rf {} +
    done
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00644 $installdir/usr/share/lbry-desktop
    cp -R dist/linux-unpacked/* $installdir/usr/share/lbry-desktop/
    ln -s /usr/share/lbry-desktop/lbry $installdir/usr/bin/lbry
    install -Dm00644 $pkgfiles/lbry-desktop.desktop $installdir/usr/share/applications/lbry-desktop.desktop
    install -Dm00644 build/icons/256x256.png $installdir/usr/share/pixmaps/lbry.png
